# Note that this file should be named application.yml - it won't work otherwise
server:
  port: 18888

spring:
  cloud:
    config:
      server:
        git :
          uri: https://github.com/RamanujamTeam/translator-service
